// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package capBook

type NewAuthor struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
}

type NewBook struct {
	LocationID     int    `json:"locationID"`
	OwnerID        int    `json:"ownerID"`
	AuthorID       int    `json:"authorID"`
	PublisherID    int    `json:"publisherID"`
	Title          string `json:"title"`
	Isbn           string `json:"isbn"`
	Edition        int    `json:"edition"`
	IsFree         bool   `json:"is_free"`
	DescriptionURL string `json:"description_url"`
}

type NewLocation struct {
	Building string `json:"building"`
	Room     string `json:"room"`
}

type NewPublisher struct {
	Name string `json:"name"`
}

type NewRental struct {
	BookID          int    `json:"bookID"`
	UserID          int    `json:"userID"`
	StartDate       string `json:"start_date"`
	ExpectedEndDate string `json:"expected_end_date"`
	EndDate         string `json:"end_date"`
}

type NewUser struct {
	Name     string `json:"name"`
	Surname  string `json:"surname"`
	Email    string `json:"email"`
	Password string `json:"password"`
	IsAdmin  bool   `json:"is_admin"`
}
