// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package capBook

type Author struct {
	AuthorID string `json:"author_id"`
	Name     string `json:"name"`
	Surname  string `json:"surname"`
}

type Book struct {
	BookID         string    `json:"book_id"`
	Location       Location  `json:"location"`
	Owner          User      `json:"owner"`
	Author         Author    `json:"author"`
	Publisher      Publisher `json:"publisher"`
	Title          string    `json:"title"`
	Isbn           string    `json:"isbn"`
	Edition        int       `json:"edition"`
	IsFree         bool      `json:"is_free"`
	DescriptionURL string    `json:"description_url"`
}

type Location struct {
	LocationID string `json:"location_id"`
	Building   string `json:"building"`
	Room       string `json:"room"`
}

type NewPublisher struct {
	Name string `json:"name"`
}

type NewUser struct {
	Name    string `json:"name"`
	Surname string `json:"surname"`
	Email   string `json:"email"`
	IsAdmin bool   `json:"is_admin"`
}

type Publisher struct {
	PublisherID string `json:"publisher_id"`
	Name        string `json:"name"`
}

type Rental struct {
	RentalID        string  `json:"rental_id"`
	Book            Book    `json:"book"`
	User            User    `json:"user"`
	StartDate       string  `json:"start_date"`
	ExpectedEndDate string  `json:"expected_end_date"`
	EndDate         *string `json:"end_date"`
}

type User struct {
	UserID  string `json:"user_id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
	Email   string `json:"email"`
	IsAdmin bool   `json:"is_admin"`
}
